
replicaCount: 1

deployment: 
      name: notification
image:
  repository:  madaurus/notification
  pullPolicy: IfNotPresent
  tag: "v1.1.0"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: notification

    
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


# Writing Max resources for simple go app
resources: 
  limits:
    cpu: 160m
    memory: 260Mi
  requests:
    cpu: 110m
    memory: 220Mi


livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 8  
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 8
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4 
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}







secrets: 
    enabled: true
    name: notification-secrets
    data:
      JWT_SECRET: oXpyiGrnL3O6AUa9b7eyTohpFeSBzQLwWHEzTJZ71x8=


container:
  name: notification
  port: 3000
  containerPort: 3000
  env:
        -  name: ENVIRONMENT
           valueFrom:
            configMapKeyRef:
              name: notification-config
              key: "environment" 
        -  name: JWT_SECRET
           valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: "JWT_SECRET"
        - name: PERMIT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: "PERMIT_TOKEN"
        - name: PDP_SERVER
          value: http://pdp-madaurus       
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: "KAFKA_BROKER"    
        - name: KAFKA_GROUP_ID
          value: notification-group     
        - name: database_uri
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: "database_uri"           


configmap:
    enabled: true
    name: notification-config
    data:
      environment: "production"
      sentry_dsn: "https://1168f4da88bba3f9669f88cbcc76cc11@o4506915435053056.ingest.us.sentry.io/4506994124713000"
      PDP_SERVER: http://localhost:7766
      database_uri: "mongodb+srv://madaurus:bbbb45@madaurus.nredljo.mongodb.net/notification?retryWrites=true&w=majority&appName=madaurus"
      KAFKA_BROKER: "kafka-cluster-kafka-brokers:9092"
      PERMIT_TOKEN: permit_key_dyl2zhOIm2EXssDKP33JGbqGKKPiZarQjl0AcL7ZYvsYsLz2zFGDWcdRghccmR0EEJF5TS8c99g5ItDHl87alV



pvc:
  enabled: false
  name:  notification-pvc
  volumeName: notification-pv
  accessModes: ReadWriteOnce
  storage: 1Gi
  storageLimit: 1.2Gi

pv: 
  enabled: false
  name: notification-pv
  storage: 1.6Gi
  mode: ReadWriteOnce
  hostPath: /data/app/notification  
