{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.name}}
  namespace: madaurus
data:
{{- with .Values.configmap.data}}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}