# Create Presistent Volume template for Database
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }} # Specify storage capacity
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.hostPath }} # Specify the path on the host
    type: Directory # Set type to Directory


