
{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: madaurus
  name: {{ .Values.pvc.name }}
spec:
  volumeName: {{ .Values.pvc.volumeName }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
    limits:
      storage: {{ .Values.pvc.storageLimit }}  

{{- end }}
