
{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: madaurus
  name: {{ .Values.pvc.name }}
spec:
  storageClassName: maduarus-sc # Constant value for now
  volumeName: {{ .Values.pvc.volumeName }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}

{{- end }}
