kind: PresistentVoluemClaim
apiVersion: v1
metadata:
  name: { { .Values.pvc.name } }
spec:
  storageClassName: maduarus-sc # Constant value for now
  volumeName: { { .Values.pvc.volumeName } }
  accessModes:
    - { { .Values.pvc.accessModes } }
  resources:
    requests:
    storage: { { .Values.pvc.storage } }
