name: Test  Helm Charts

on:
  push:
    branches:
      - master
env: 
    AZURE_REGISTRY: madaurus.azurecr.io
    AZURE_REGISTRY_USER: madaurus
    AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    CHART_NAME: madaurus
    CHART_VERSION: 0.1.0
    environment: dev
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Sync With Github Repo
              uses: actions/checkout@v3  
            # - name: Login to ACR using Helm
              # run: echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | helm registry login ${{ env.AZURE_REGISTRY }} --username ${{ env.AZURE_REGISTRY_USER }} --password-stdin
            - name: Test Helm With materials Values
              run: helm lint . -f material.${{ env.environment }}.values.yaml
            - name: Test Helm With staff Values
              run: helm lint . -f staff.${{ env.environment }}.values.yaml              
            
        
                

        
                        
        



